language: node_js
node_js:
  - node
dist: bionic
sudo: required
branches:
  only:
   - master
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod --base-href https://Capttan.github.io/myform/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/myform
  on:
    branch: master

notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always
    # template:
    #   - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    #   - "Change view : %{compare_url}"
    #   - "Build details : %{build_url}"
